// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yuhzboxicaizdcybbkdm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl1aHpib3hpY2FpemRjeWJia2RtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI3NTYzNzQsImV4cCI6MjA1ODMzMjM3NH0.74hMzAkyYWnyOlGmjYGKobHtGa7EVoXhzEVl-IH2VN8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);