// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bfumotyazjgyaqzsjial.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJmdW1vdHlhempneWFxenNqaWFsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIwNTA5MDcsImV4cCI6MjA1NzYyNjkwN30.bqKsfDdviyQamALRbTP2iwF3e93GIWYr5ypm4Dt3tVc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);